### ISSUE TITLE
Review of Fundermentals Training Environment 

### ISSUE THREAD

**Issue by Jayclifford345** [grafana/killercoda#1]
Any issues/changes to the course for the Fundamentals training environment?

**Comment by mdcruz** [comment]
![Screenshot 2024-03-20 at 10 53 44](https://github.com/grafana/killercoda/assets/10811379/bdea9a41-67dd-42a6-a656-a153cfbd8ced)

Message should say "Grafana Fundamentals"

**Comment by mdcruz** [comment]
"This URL will direct you to the simulator for this tutorial. This simulator lets you post links and vote for the ones you like. This is important for generating traffic and errors to populate our Grafana dashboards."

- maybe instead of simulator, we can say "This URL will direct you to the sample application for this tutorial. Grafana News lets you..."

**Comment by Jayclifford345** [comment]
Legend! @mdcruz, thank you for those catches. Thats both suggestions changed and committed.
