### ISSUE TITLE
docs: Decide whether users should only specify intro and finish tags in the docs rather than details

### ISSUE THREAD

**Issue by Jayclifford345** [grafana/killercoda#23]
Seems to me I would always prefer to use into/finish directives and not separate files to make sure docs is "single source of truth".  Curious if you guys see it another way.  Docs usually have this "connective tissue" (an intro to the page, and what to do next at the bottom).   If I'm maintaining killercoda & docs in one markdown file in the git repo, it seems to me vastly superior that I define those directives just in the docs, and not try to write separate content in another repo (killercoda).   Though this raises a possible question: if I need totally different "next steps" at the end of a killercoda, I might need a way of hiding it from docs.  Like the opposite of an "ignore" -- something like "ignore this bit from docs and only put it in the killercoda".  That might be complicated tho

**Comment by jdbaldry** [comment]
We do have the include directive which includes content only in the Killercoda course and not the docs but the its not very ergonomic for long form content because every line must be within HTML comments.

At the moment, users have the flexibility to specify a separate intro or finish, or use the directives in the docs and the docs directives take precedence. I should document that in https://github.com/grafana/killercoda/blob/staging/docs/transformer.md#intro.

**Comment by jdbaldry** [comment]
https://github.com/grafana/killercoda/pull/33
